{% set name = "libhwloc" %}
{% set version = "1.11.2" %}
{% set sha256 = "d11f091ed54c56c325ffca1083113a405fcd8a25d5888af64f5cd6cf587b7b0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/hwloc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
  - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config                # [unix]
    - posix                     # [win]
    - clangdev                  # [win]
    - llvmdev                   # [win]
    - lld                       # [win]
    - m2-perl                   # [win]
    - m2-automake-wrapper       # [win]
    - m2-libtool                # [win]
    - m2-autoconf               # [win]
    - m2-make                   # [win]
    - m2-m4                     # [win]
    - python >3                 # [win]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
    - pthreads-win32            # [win]
  run:
    - libxml2
    - pthreads-win32            # [win]

test:
  commands:
    - hwloc-ls

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD 3-Clause
  license_file: COPYING
  summary: 'Portable Hardware Locality (hwloc)'

extra:
  recipe-maintainers:
    - inducer
    - isuruf
